name: Build Multi-Arch Images

on:
  push:
    branch:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPOSITORY: ghcr.io/eric-convergence/blockscout-eth

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v1.6.0
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Enable Docker Buildx
        run: |
          jq '. + {"experimental":"enabled"}' ~/.docker/config.json > ~/.docker/config_new.json
          mv ~/.docker/config_new.json ~/.docker/config.json
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          sudo systemctl restart docker
          docker buildx create --name multi_builder
          docker buildx use multi_builder

      - name: Build linux/amd64 Image
        run: |
          docker buildx build -t ${DOCKER_REPOSITORY}:latest-amd64 --platform linux/amd64 --output=type=docker ./docker

      - name: Build linux/arm64 Image
        run: |
          docker buildx build -t ${DOCKER_REPOSITORY}:latest-arm64 --platform linux/arm64 --output=type=docker ./docker

      - name: Push Multi-Arch Images
        run: |
          docker push ${DOCKER_REPOSITORY}:latest-amd64
          docker push ${DOCKER_REPOSITORY}:latest-arm64
          docker manifest create ${DOCKER_REPOSITORY}:latest \
            ${DOCKER_REPOSITORY}:latest-amd64 \
            ${DOCKER_REPOSITORY}:latest-arm64
          docker manifest create ${DOCKER_REPOSITORY}:latest \
            ${DOCKER_REPOSITORY}:latest-amd64 \
            ${DOCKER_REPOSITORY}:latest-arm64
          docker manifest push ${DOCKER_REPOSITORY}:latest
